-- init locales
lib.locale()

Config = Config or {}

Config.Job = {}

---@type JobOptions
Config.Job.Mining = {
    id = "Mining",
    name = locale("MINING_JOB_LABEL"),
    vehicleRent = 50,
    customRep = {
        { label = locale("SHOW_RANK", "1"), value = 1000 },
        { label = locale("SHOW_RANK", "2"), value = 2000 },
        { label = locale("SHOW_RANK", "3"), value = 3000 },
        { label = locale("SHOW_RANK", "4"), value = 4000 },
        { label = locale("SHOW_RANK", "5"), value = 5000 },
        { label = locale("SHOW_RANK", "6"), value = 6000 },
        { label = locale("SHOW_RANK", "7"), value = 7000 },
        { label = locale("SHOW_RANK", "8"), value = 8000 },
        { label = locale("SHOW_RANK", "9"), value = 9000 },
        { label = locale("SHOW_RANK", "10"), value = 10000 },
    },
    doublePayChance = {
        [0] = 0,
        [1] = 0.05,
        [2] = 0.05,
        [3] = 0.1,
        [4] = 0.1,
        [5] = 0.15,
        [6] = 0.15,
        [7] = 0.2,
        [8] = 0.2,
        [9] = 0.25,
        [10] = 0.25,
    },
    speedIncrease = {
        [0] = 0,
        [1] = 0,
        [2] = 0.04,
        [3] = 0.04,
        [4] = 0.08,
        [5] = 0.08,
        [6] = 0.12,
        [7] = 0.12,
        [8] = 0.16,
        [9] = 0.16,
        [10] = 0.2,
    },
    miningCenter = {
        pedCoords = vector4(2601.064209, 2804.468262, 32.823254, 197.521210),
        pedModel = "s_m_y_construct_01",
        vehSpawns = {
            vector4(2592.429443, 2804.954590, 33.563995, 191.645874)
        }
    },
    cleaningCenter = {
        pedCoords = vector4(287.786316, 2843.881592, 43.704113, 125.780663),
        pedModel = "s_m_y_construct_01",
        processTime = 12000,
    },
    vehicleModel = `bison`,
}

Config.RequiredRepLevel = {
    ["weapon_pickaxe"] = 0,
    ["weapon_drill"] = 0,
    ["weapon_drill_cobalt"] = 0,
    ["weapon_drill_hss"] = 4,
    ["weapon_drill_diamond"] = 5,
}

Config.RepReward = { -- per item (value * quantity) when selling at the ore seller
    ["iron"] = 2,
    ["copper"] = 2,
    ["zinc"] = 5,
    ["chromium"] = 5,
    ["nickel"] = 5,
    ["lithium"] = 5,
    ["aluminium"] = 5,
    ["magnesium"] = 5,
    ["gold"] = 5,
    ["diamond"] = 5,
    ["limestone"] = 2,
}

Config.MiningZones = {
    {
        name = "quarry_mining_zone",
        label = locale("QUARY_MINING_ZONE_LABEL"),
        maxOres = 25,
        ores = {
            { 55, "iron" },
            { 45, "copper" },
        },
        boxZone = {
            coords = vec3(2952.0, 2789.0, 41.0),
            size = vec3(46.0, 54.0, 4.0),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(2964.7, 2755.1, 42.3, 127.4),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    {
        name = "paleto_bay_1",
        label = locale("PALETO_MINING_ZONE_LABEL"),
        maxOres = 20,
        ores = {
            { 42, "iron" },
            { 33, "copper" },
            { 10, "aluminium" },
            { 9, "zinc" },
            { 4, "lithium" },
            { 1, "gold" },
            { 1, "diamond" },
        },
        boxZone = {
            coords = vec3(192.0, 6944.0, 11.0),
            size = vec3(28.0, 36.0, 8.0),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(212.3, 6935.8, 10.7, 268.8),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    {
        name = "swamp_2",
        label = locale("SWAMP_MINING_ZONE_LABEL"),
        maxOres = 20,
        ores = {
            { 36, "iron" },
            { 28, "copper" },
            { 15, "aluminium" },
            { 10, "zinc" },
            { 7, "lithium" },
            { 6, "nickel" },
            { 7, "magnesium" },
            { 9, "limestone" },
            { 1, "gold" },
            { 1, "diamond" },
        },
        boxZone = {
            coords = vec3(-2480.0, 2789.0, 3.0),
            size = vec3(107.0, 105.0, 4.0),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(-2497.7, 2818.5, 2.4, 35.4),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    {
        name = "stab_city",
        label = locale("STAB_CITY_MINING_ZONE_LABEL"),
        maxOres = 20,
        ores = {
            { 37, "iron" },
            { 28, "copper" },
            { 15, "aluminium" },
            { 10, "zinc" },
            { 7, "lithium" },
            { 5, "nickel" },
            { 7, "magnesium" },
            { 9, "limestone" },
            { 1, "gold" },
            { 1, "diamond" },
        },
        boxZone = {
            coords = vec3(-63.0, 3686.0, 50.0),
            size = vec3(71.0, 92.0, 36),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(-40.1, 3692.4, 36.4, 270.1),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    {
        name = "raday_aray",
        label = locale("RADAR_ARRAY_MINING_ZONE_LABEL"),
        maxOres = 20,
        ores = {
            { 61, "iron" },
            { 28, "copper" },
            { 5, "aluminium" },
            { 4, "zinc" },
            { 1, "gold" },
            { 1, "diamond" },
        },
        boxZone = {
            coords = vec3(2034.0, 2798.0, 50.0),
            size = vec3(79.0, 77.0, 4.0),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(2053.8, 2828.5, 48.0, 163.6),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    {
        name = "union_road",
        label = locale("UNION_ROAD_MINING_ZONE_LABEL"),
        maxOres = 20,
        ores = {
            { 62, "iron" },
            { 26, "copper" },
            { 5, "aluminium" },
            { 5, "zinc" },
            { 1, "gold" },
            { 1, "diamond" },
        },
        boxZone = {
            coords = vec3(2945.0, 4551.0, 49.0),
            size = vec3(35.0, 46.0, 12.0),
            rotation = 0.0,
        },
        storage = {
            coords = vec4(2924.7, 4544.8, 48.8, 31.8),
            prop = `prop_dumpster_02b`,
            label = locale("OPEN_ORE_STORAGE"),
            renderDistance = 50,
            maxSlots = 20,
            maxWeight = 100,
        },
    },
    -- {
    --     name = "gem_mining_zone",
    --     label = locale("TUNNEL_MINING_ZONE"),
    --     maxOres = 7,
    --     ores = {
    --         { 58, "iron" },
    --         { 22, "copper" },
    --         { 5, "aluminium" },
    --         { 10, "zinc" },
    --         { 3, "gold" },
    --         { 2, "diamond" },
    --     },
    --     isGemZone = true,
    --     boxZone = {
    --         coords = vec3(2952.0, 2789.0, 41.0),
    --         size = vec3(30.0, 30.0, 4.0),
    --         rotation = 0.0,
    --     },
    -- },
}

Config.TunnelRooms = {
    "ladder1_",
    "section1_",
    "section1b_",
    "section2_",
    "section3_",
    "section4_",
    "section5_",
    "section6_",
    "section7_",
    "section8_",
    "section9_",
    "section10_",
    "section11_",
    "section12_",
    "section13_",
    "sideroom1_",
    "sideroom2_",
    "sideroom3_",
    "sideroom4_",
}

Config.TunnelGems = {
    { 62, "iron" },
    { 26, "copper" },
    { 5, "aluminium" },
    { 5, "zinc" },
    { 1, "gold" },
    { 1, "diamond" },
}

Config.RequiredLevelForGems = 5

Config.Gems = {
    ["sapphire"] = {
        label = locale("SAPPHIRE"),
        invRarity = "COMMON",
        rarity = 10,
        quality = {
            ["dirty"] = {
                label = locale("DIRTY"),
                rarity = 5,
                minQuality = 0,
                maxQuality = 24,
                sellPrice = 25,
            },
            ["common"] = {
                label = locale("COMMON"),
                rarity = 20,
                minQuality = 25,
                maxQuality = 49,
                sellPrice = 35,
            },
            ["uncommon"] = {
                label = locale("UNCOMMON"),
                rarity = 20,
                minQuality = 50,
                maxQuality = 79,
                sellPrice = 45,
            },
            ["clear"] = {
                label = locale("CLEAR"),
                rarity = 45,
                minQuality = 80,
                maxQuality = 99,
                sellPrice = 55,
            },
            ["perfect"] = {
                label = locale("PERFECT"),
                rarity = 10,
                minQuality = 100,
                maxQuality = 100,
                sellPrice = 85,
            },
        }
    },
    ["ruby"] = {
        label = locale("RUBY"),
        invRarity = "COMMON",
        rarity = 30,
        quality = {
            ["dirty"] = {
                label = locale("DIRTY"),
                rarity = 5,
                minQuality = 0,
                maxQuality = 24,
                sellPrice = 15,
            },
            ["common"] = {
                label = locale("COMMON"),
                rarity = 20,
                minQuality = 25,
                maxQuality = 49,
                sellPrice = 20,
            },
            ["uncommon"] = {
                label = locale("UNCOMMON"),
                rarity = 20,
                minQuality = 50,
                maxQuality = 79,
                sellPrice = 30,
            },
            ["clear"] = {
                label = locale("CLEAR"),
                rarity = 45,
                minQuality = 80,
                maxQuality = 99,
                sellPrice = 55,
            },
            ["perfect"] = {
                label = locale("PERFECT"),
                rarity = 10,
                minQuality = 100,
                maxQuality = 100,
                sellPrice = 85,
            },
        }
    },
    ["emerald"] = {
        label = locale("EMERALD"),
        invRarity = "COMMON",
        rarity = 30,
        quality = {
            ["dirty"] = {
                label = locale("DIRTY"),
                rarity = 5,
                minQuality = 0,
                maxQuality = 24,
                sellPrice = 25,
            },
            ["common"] = {
                label = locale("COMMON"),
                rarity = 20,
                minQuality = 25,
                maxQuality = 49,
                sellPrice = 35,
            },
            ["uncommon"] = {
                label = locale("UNCOMMON"),
                rarity = 20,
                minQuality = 50,
                maxQuality = 79,
                sellPrice = 45,
            },
            ["clear"] = {
                label = locale("CLEAR"),
                rarity = 45,
                minQuality = 80,
                maxQuality = 99,
                sellPrice = 55,
            },
            ["perfect"] = {
                label = locale("PERFECT"),
                rarity = 10,
                minQuality = 100,
                maxQuality = 100,
                sellPrice = 85,
            },
        }
    },
    -- ["diamond"] = {
    --     label = "Diamond",
    --     invRarity = "COMMON",
    --     rarity = 0,
    --     quality = {
    --         ["dirty"] = {
    --             label = "Dirty",
    --             rarity = 20,
    --             minQuality = 0,
    --             maxQuality = 24,
    --             sellPrice = 25,
    --         },
    --         ["common"] = {
    --             label = "Common",
    --             rarity = 40,
    --             minQuality = 25,
    --             maxQuality = 49,
    --             sellPrice = 35,
    --         },
    --         ["uncommon"] = {
    --             label = "Uncommon",
    --             rarity = 20,
    --             minQuality = 50,
    --             maxQuality = 79,
    --             sellPrice = 45,
    --         },
    --         ["clear"] = {
    --             label = "Clear",
    --             rarity = 20,
    --             minQuality = 80,
    --             maxQuality = 99,
    --             sellPrice = 55,
    --         },
    --         ["perfect"] = {
    --             label = "Perfect",
    --             rarity = 20,
    --             minQuality = 100,
    --             maxQuality = 100,
    --             sellPrice = 55,
    --         },
    --     }
    -- },
    ["topaz"] = {
        label = locale("TOPAZ"),
        invRarity = "COMMON",
        rarity = 30,
        quality = {
            ["dirty"] = {
                label = locale("DIRTY"),
                rarity = 5,
                minQuality = 0,
                maxQuality = 24,
                sellPrice = 25,
            },
            ["common"] = {
                label = locale("COMMON"),
                rarity = 20,
                minQuality = 25,
                maxQuality = 49,
                sellPrice = 35,
            },
            ["uncommon"] = {
                label = locale("UNCOMMON"),
                rarity = 20,
                minQuality = 50,
                maxQuality = 79,
                sellPrice = 45,
            },
            ["clear"] = {
                label = locale("CLEAR"),
                rarity = 45,
                minQuality = 80,
                maxQuality = 99,
                sellPrice = 55,
            },
            ["perfect"] = {
                label = locale("PERFECT"),
                rarity = 10,
                minQuality = 100,
                maxQuality = 100,
                sellPrice = 85,
            },
        }
    },
}

Config.InventoryRarity = {
    ["dirty"] = "COMMON",
    ["common"] = "UNCOMMON",
    ["uncommon"] = "RARE",
    ["clear"] = "EPIC",
    ["perfect"] = "LEGENDARY",
}

Config.TunnelSpots = {
    vector3(2967.642, 3040.942, 39.011),
    vector3(2953.60327, 3057.64014, 37.98229),
    vector3(2933.20386, 3078.02539, 37.93301),
    vector3(2875.05688, 3119.02246, 38.16228),
    vector3(2873.57056, 3121.25366, 38.16293),
    vector3(2875.21973, 3122.93042, 38.16276),
    vector3(2877.00635, 3120.31738, 38.16178),
    vector3(2784.18188, 3231.31226, 37.93347),
    vector3(2774.40161, 3240.12915, 37.99091),
    vector3(2744.79248, 3276.28857, 37.96322),
    vector3(2634.06689, 3410.91284, 38.16279),
    vector3(2631.99121, 3409.4917, 38.16277),
    vector3(2634.22388, 3407.12695, 38.16164),
    vector3(2622.45288, 3511.16504, 38.06524),
    vector3(2603.05322, 3545.26538, 38.16762),
    vector3(2601.48169, 3543.68872, 38.16279),
    vector3(2603.27344, 3541.06665, 38.16167),
    vector3(2603.6814, 3542.89478, 38.16211),
    vector3(2586.07471, 3619.59888, 38.16443),
    vector3(2584.48267, 3618.14917, 38.16278),
    vector3(2585.19507, 3616.18555, 38.16215),
    vector3(2587.19116, 3615.73804, 38.16184),
    vector3(2586.76074, 3617.50244, 38.16211),
    vector3(2555.08765, 3753.60107, 38.16721),
    vector3(2553.42212, 3752.18506, 38.16286),
    vector3(2553.62305, 3749.93384, 38.16229),
    vector3(2555.89941, 3749.729, 38.16177),
    vector3(2555.55469, 3751.44775, 38.16224),
    vector3(2537.86938, 3876.75464, 39.40302),
    vector3(2539.72705, 3876.94995, 39.39601),
    vector3(2541.43921, 3866.12646, 39.40303),
    vector3(2543.34985, 3866.78247, 39.40173),
    vector3(2545.12988, 3854.927, 39.2041),
    vector3(2549.28003, 3849.97583, 39.05813),
    vector3(2550.54541, 3843.62939, 38.97617),
    vector3(2556.60083, 3835.6748, 38.90238),
    vector3(2557.85474, 3830.45874, 38.87531),
    vector3(2563.11304, 3822.06055, 38.87345),
    vector3(2559.75708, 3811.7561, 38.78615),
    vector3(2558.57031, 3804.7229, 38.61824),
    vector3(2555.72192, 3795.4397, 38.01058),
    vector3(2558.72217, 3785.7439, 38.01659),
    vector3(2559.70703, 3775.95068, 37.9999),
    vector3(2563.8877, 3764.02832, 38.05776),
    vector3(2566.38232, 3747.77051, 38.02145),
}

Config.GemsNPC = {
    pos = vector4(-621.618, -231.883, 37.077, 118.973),
    model = `a_m_y_smartcaspat_01`,
}

Config.GemsInteraction = {
    pos = vector4(-702.5, -895.39, 18.69, 0.0),
    width = 3.2,
    length = 1.2,
    minZ = 17.69,
    maxZ = 19.49,
}

Config.MiningWeapons = {
    [`WEAPON_PICKAXE`] = {
        damage = {
            ["aluminium"] = 10,
            ["chromium"] = 10,
            ["copper"] = 10,
            ["iron"] = 10,
            ["lithium"] = 10,
            ["magnesium"] = 10,
            ["nickel"] = 10,
            ["steel"] = 10,
            ["zinc"] = 10,
            ["gold"] = 10,
            ["diamond"] = 10,
            ["limestone"] = 10,
            ["basic_looking"] = 10,
            ["gem"] = 10,
        },
        debounce = 0
    },
    [`WEAPON_DRILL`] = {
        isDrill = true,
        damage = {
            ["aluminium"] = 1,
            ["chromium"] = 1,
            ["copper"] = 1,
            ["iron"] = 1,
            ["lithium"] = 1,
            ["magnesium"] = 1,
            ["nickel"] = 1,
            ["steel"] = 1,
            ["zinc"] = 1,
            ["gold"] = 1,
            ["diamond"] = 1,
            ["limestone"] = 1,
            ["basic_looking"] = 1,
            ["gem"] = 1,
        },
        item = 'WEAPON_DRILL',
        bonusDamage = 0.0,
        durabilityDrain = 0.01,
        heating = 0.005,
        coolOffTime = 3.0, -- seconds
        overheatMultiplier = 10.0,
        overlayColor = "#ffffff00",
        debounce = 300
    },
    [`WEAPON_DRILL_COBALT`] = {
        isDrill = true,
        damage = {
            ["aluminium"] = 1,
            ["chromium"] = 1,
            ["copper"] = 1,
            ["iron"] = 1,
            ["lithium"] = 1,
            ["magnesium"] = 1,
            ["nickel"] = 1,
            ["steel"] = 1,
            ["zinc"] = 1,
            ["gold"] = 1,
            ["diamond"] = 1,
            ["limestone"] = 1,
            ["basic_looking"] = 1,
            ["gem"] = 1,
        },
        item = 'WEAPON_DRILL_COBALT',
        bonusDamage = 0.1,
        durabilityDrain = 0.005,
        heating = 0.005,
        coolOffTime = 5.0, -- seconds
        overheatMultiplier = 7.5,
        overlayColor = "#FFD70078",
        debounce = 300
    },
    [`WEAPON_DRILL_HSS`] = {
        isDrill = true,
        damage = {
            ["aluminium"] = 1,
            ["chromium"] = 1,
            ["copper"] = 1,
            ["iron"] = 1,
            ["lithium"] = 1,
            ["magnesium"] = 1,
            ["nickel"] = 1,
            ["steel"] = 1,
            ["zinc"] = 1,
            ["gold"] = 1,
            ["diamond"] = 1,
            ["limestone"] = 1,
            ["basic_looking"] = 1,
            ["gem"] = 1,
        },
        item = 'WEAPON_DRILL_HSS',
        bonusDamage = 0.1,
        durabilityDrain = 0.005,
        heating = 0.0025,
        coolOffTime = 5.0, -- seconds
        overheatMultiplier = 5.0,
        overlayColor = "#3230ab78",
        debounce = 300
    },
    [`WEAPON_DRILL_DIAMOND`] = {
        isDrill = true,
        damage = {
            ["aluminium"] = 1,
            ["chromium"] = 1,
            ["copper"] = 1,
            ["iron"] = 1,
            ["lithium"] = 1,
            ["magnesium"] = 1,
            ["nickel"] = 1,
            ["steel"] = 1,
            ["zinc"] = 1,
            ["gold"] = 1,
            ["diamond"] = 1,
            ["limestone"] = 1,
            ["basic_looking"] = 1,
            ["gem"] = 1,
        },
        item = 'WEAPON_DRILL_DIAMOND',
        bonusDamage = 0.2,
        durabilityDrain = 0.002,
        heating = 0.00075,
        coolOffTime = 2.0, -- seconds
        overheatMultiplier = 2.5,
        overlayColor = "#53e3fc78",
        debounce = 300
    },
}

Config.DefaultOreRepByRarity = {
    COMMON = 1,
    UNCOMMON = 2,
    RARE = 3,
    EPIC = 4,
    LEGENDARY = 5,
}

Config.Ores = {
    lithium = {
        label = locale("LITHIUM_ITEM_LABEL"),
        rarity = "EPIC",
        weight = 5.0,
        stackable = 50,
        price = 45,
        reputationReward = 50,
        sellPrice = 50,
        dropMin = 1,
        dropMax = 1,
    },
    nickel = {
        label = locale("NICKEL_ITEM_LABEL"),
        rarity = "RARE",
        stackable = 50,
        weight = 5.0,
        price = 38,
        reputationReward = 50,
        allowedDrills = { [`WEAPON_DRILL_HSS`] = true },
        sellPrice = 35,
        dropMin = 1,
        dropMax = 2,
    },
    magnesium = {
        label = locale("MAGNESIUM_ITEM_LABEL"),
        rarity = "EPIC",
        weight = 5.0,
        stackable = 50,
        price = 45,
        reputationReward = 50,
        sellPrice = 45,
        dropMin = 1,
        dropMax = 1,
    },
    iron = {
        label = locale("IRON_ITEM_LABEL"),
        rarity = "COMMON",
        weight = 5.0,
        stackable = 50,
        price = 15,
        reputationReward = 50,
        sellPrice = 8,
        dropMin = 2,
        dropMax = 4,
    },
    aluminium = {
        label = locale("ALUMINIUM_ITEM_LABEL"),
        rarity = "UNCOMMON",
        weight = 5.0,
        price = 25,
        stackable = 50,
        reputationReward = 50,
        drillOnly = true,
        allowedDrills = { [`WEAPON_DRILL_COBALT`] = true },
        sellPrice = 16,
        dropMin = 1,
        dropMax = 3,
    },
    copper = {
        label = locale("COPPER_ITEM_LABEL"),
        rarity = "COMMON",
        weight = 5.0,
        price = 18,
        stackable = 50,
        reputationReward = 50,
        sellPrice = 10,
        dropMin = 2,
        dropMax = 4,
    },
    zinc = {
        label = locale("ZINC_ITEM_LABEL"),
        rarity = "RARE",
        stackable = 50,
        weight = 5.0,
        price = 35,
        reputationReward = 50,
        sellPrice = 28,
        dropMin = 1,
        dropMax = 2,
    },
    gold = {
        label = locale("GOLD_ITEM_LABEL"),
        rarity = "LEGENDARY",
        stackable = 50,
        weight = 5.0,
        price = 80,
        reputationReward = 50,
        allowedDrills = { [`WEAPON_DRILL_DIAMOND`] = true },
        sellPrice = 85,
        dropMin = 1,
        dropMax = 1,
    },
    diamond = {
        label = locale("DIAMOND_ITEM_LABEL"),
        rarity = "LEGENDARY",
        stackable = 50,
        weight = 5.0,
        price = 100,
        reputationReward = 50,
        allowedDrills = { [`WEAPON_DRILL_DIAMOND`] = true },
        sellPrice = 120,
        dropMin = 1,
        dropMax = 1,
    },
    limestone = {
        label = locale("LIMESTONE_ITEM_LABEL"),
        rarity = "RARE",
        weight = 5.0,
        price = 15,
        stackable = 50,
        reputationReward = 50,
        sellPrice = 24,
        dropMin = 1,
        dropMax = 2,
    },
    basic_looking = {
        label = locale("STONE_ITEM_LABEL"),
        rarity = "UNCOMMON",
        weight = 5.0,
        price = 8,
        stackable = 50,
        reputationReward = 50,
        sellPrice = 6,
        dropMin = 1,
        dropMax = 3,
    },
    gem = {
        label = locale("GEM_ITEM_LABEL"),
        rarity = "RARE",
        weight = 5.0,
        price = 15,
        stackable = 50,
        reputationReward = 50,
        sellPrice = 14,
        dropMin = 1,
        dropMax = 2,
    },
}

Config.InventoryItems = {
    -- WEAPON_PICKAXE = {
    --     label = locale("WEAPON_PICKAXE_ITEM_LABEL"),
    --     rarity = "COMMON",
    --     weaponHash = `WEAPON_PICKAXE`,
    --     weight = 5.0,
    --     model = `w_me_pickaxe`,
    --     type = 2,
    --     price = 100,
    --     noSerial = true,
    --     stackable = false
    -- },
    -- WEAPON_DRILL = {
    --     label = locale("WEAPON_DRILL_ITEM_LABEL"),
    --     rarity = "COMMON",
    --     weaponHash = `WEAPON_DRILL`,
    --     weight = 5.0,
    --     model = `w_prp_drill`,
    --     type = 2,
    --     price = 100,
    --     noSerial = true,
    --     stackable = false,
    --     isContainer = true,
    -- },
}

Config.AttachOffsets = {
    [`bison`] = {
        ["ore_1"] = {
            offset = vector3(0.0, -1.0, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_2"] = {
            offset = vector3(-0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_3"] = {
            offset = vector3(0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_4"] = {
            offset = vector3(0.0, -1.8, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_5"] = {
            offset = vector3(-0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_6"] = {
            offset = vector3(0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
    },
    [`bison2`] = {
        ["ore_1"] = {
            offset = vector3(0.0, -1.0, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_2"] = {
            offset = vector3(-0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_3"] = {
            offset = vector3(0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_4"] = {
            offset = vector3(0.0, -1.8, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_5"] = {
            offset = vector3(-0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_6"] = {
            offset = vector3(0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
    },
    [`bison3`] = {
        ["ore_1"] = {
            offset = vector3(0.0, -1.0, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_2"] = {
            offset = vector3(-0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_3"] = {
            offset = vector3(0.4, -1.6, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_4"] = {
            offset = vector3(0.0, -1.8, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_5"] = {
            offset = vector3(-0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_6"] = {
            offset = vector3(0.4, -2.2, 0.5),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
    },
    [`bobcatxl`] = {
        ["ore_1"] = {
            offset = vector3(0.0, -1.2, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_2"] = {
            offset = vector3(-0.5, -1.0, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_3"] = {
            offset = vector3(0.5, -1.0, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_4"] = {
            offset = vector3(0.0, -1.8, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_5"] = {
            offset = vector3(-0.3, -2.4, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
        ["ore_6"] = {
            offset = vector3(0.3, -2.4, 0.25),
            rot = vector3(0.0, 0.0, 0.0),
            bone = 0,
        },
    },
}

for k, v in pairs(Config.Ores) do
    Config.InventoryItems[("%s_ore"):format(k)] = {
        label = locale("ORE_ITEM_LABEL", v.label),
        rarity = v.rarity,
        weight = v.weight,
        price = v.price,
        model = joaat("destiny_stone_bit_"..k),
        animation = {
            dictionary = "anim@heists@box_carry@",
            animation = "idle",
            prop = {
                hash = joaat("destiny_stone_bit_"..k),
                bone = 57005,
                position = vector3( 0.11, 0.195, -0.29),
                rotation = vector3(-104, -15, 38.5),
            },

            disableEnteringVehicle = true
        }
    }
    Config.InventoryItems[k] = v
end

Config.WhitelistedVehModels = {
    [`lumber`] = 6,
    [`kalahari`] = 6,
    [`bison`] = 6,
    [`bison2`] = 6,
    [`bison3`] = 6,
    [`bobcatxl`] = 6,
    [`everon`] = 6,
    [`sandking`] = 6,
    [`sandking2`] = 6,
    [`rebel`] = 6,
    [`rebel2`] = 6,
    [`caracara2`] = 6,
    [`contender`] = 6,
    [`yosemite`] = 6,
    [`yosemite2`] = 6,
    [`yosemite3`] = 6,
    [`yosemite1500`] = 6,
    [`guardian`] = 6,
    [`sadler`] = 6,
    [`sandstorm`] = 6,
    [`sandstormxl`] = 6,
    [`nsandstorm`] = 6,
    [`nsandstorm2`] = 6,
    [`hellenstorm`] = 6,
    [`l35`] = 6,
    [`caracaran`] = 6,
    [`kamacho`] = 6,
    [`dubsta3`] = 6,
    [`duneloader`] = 6,
    [`tfbison`] = 6,
    [`tfbison2`] = 6,
    [`tfbison3`] = 6,
    [`tfbison4`] = 6,
    [`dloader`] = 6,
    [`bodhi2`] = 6,
    [`firebolt`] = 6,
    [`boor`] = 6,
    [`patriot3`] = 6,
    [`squaddie`] = 6,
    [`riata`] = 6,
    [`gbbisonhf`] = 6,
    [`gbbisonstx`] = 6,
    [`gblod4`] = 6,
    [`warrener2`] = 6,
    [`gbbisonstx`] = 4, -- Pretty Small Bed - only 4
    [`gbbisonhf`] = 6,
    [`gbmojave`] = 6,
}